// Generated by CoffeeScript 1.7.1
jq$(function() {
  if (jq$('#res_table')[0]) {
    return;
  }
  return jq$.getScript("https://yacohana.github.io/sart/assets/jquery.tablesorter.min.js", function() {
    var css, data, flag, i, j, lgroup, res_table, res_tbody, res_tr, row, sgroup, show_button, sort_button, sort_rev_button, str, _i, _j, _k, _len, _len1, _len2, _ref;
    jq$("head").append('<link>');
    css = jq$("head").children(':last');
    css.attr({
      rel: 'stylesheet',
      type: 'text/css',
      href: 'https://yacohana.github.io/sart/assets/style.css'
    });
    data = [];
    jq$('tr').each(function(i) {
      data[i] = [];
      return jq$('td', jq$(this)).each(function(j) {
        return data[i][j] = jq$(this).text().trim();
      });
    });
    res_table = jq$('<table id="res_table">');
    res_tr = jq$('<tr>');
    res_tr.append('<th>分野名</th><th>系列名</th><th>科目名</th>');
    _ref = data[1];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      str = _ref[i];
      if (!(i === 0 || i === 4)) {
        res_tr.append("<th>" + str + "</th>");
      }
    }
    res_table.append(jq$('<thead>').append(res_tr));
    res_tbody = jq$('<tbody>');
    flag = false;
    for (i = _j = 0, _len1 = data.length; _j < _len1; i = ++_j) {
      row = data[i];
      if (i < 2) {
        continue;
      }
      if (row.length < 2) {
        if (flag) {
          lgroup = sgroup;
          sgroup = row[0];
        } else {
          sgroup = row[0];
        }
        flag = true;
      } else {
        flag = false;
        res_tr = jq$('<tr>');
        res_tr.append("<td>" + lgroup + "</td><td>" + sgroup + "</td>");
        for (j = _k = 0, _len2 = row.length; _k < _len2; j = ++_k) {
          str = row[j];
          if (j !== 4) {
            res_tr.append("<td>" + str + "</td>");
          }
        }
        res_tbody.append(res_tr);
      }
    }
    res_table.append(res_tbody);
    jq$("table.list").before(res_table);
    res_table.tablesorter({
      sortList: [[7, 1], [8, 1]]
    });
    show_button = jq$('<button id="show_button">元の表を表示</button>').click(function() {
      jq$("table.list").toggle();
      return false;
    });
    sort_button = jq$('<button id="sort_button">セメスター順に並べ替え</button>').click(function() {
      var sorting;
      sorting = [[7, 0], [8, 0]];
      res_table.trigger("sorton", [sorting]);
      return false;
    });
    sort_rev_button = jq$('<button id="sort_rev_button">セメスター逆順に並べ替え</button>').click(function() {
      var sorting;
      sorting = [[7, 1], [8, 1]];
      res_table.trigger("sorton", [sorting]);
      return false;
    });
    jq$("table.list").before(show_button);
    res_table.before(sort_button);
    res_table.before(sort_rev_button);
    return jq$("table.list").hide();
  });
});
